# Generated by Django 5.1.4 on 2025-01-15 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_team_todo_start_time_todo_state_todo_total_elapsed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.team'),
        ),
    ]
