# Generated by Django 5.1.4 on 2025-01-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_todo_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.team'),
        ),
    ]
