# Generated by Django 5.1.4 on 2025-01-22 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_todo_start_time_alter_todo_state'),
        ('todo_app', '0007_alter_todo_state'),
    ]

    operations = [
    ]
