# Generated by Django 5.1.4 on 2025-01-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0014_unique_members_in_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='name',
        ),
    ]
